import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
const defaultOptions = {} as const;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** An ISO 8601-encoded datetime */
  ISO8601DateTime: { input: any; output: any; }
  /** Represents untyped JSON */
  JSON: { input: any; output: any; }
};

export type AutomaticTax = {
  __typename?: 'AutomaticTax';
  enabled: Scalars['Boolean']['output'];
  liability?: Maybe<Scalars['JSON']['output']>;
  status?: Maybe<Scalars['String']['output']>;
};

/** Based on https://docs.stripe.com/api/checkout/sessions/object */
export type CheckoutSession = {
  __typename?: 'CheckoutSession';
  amountSubtotal?: Maybe<Scalars['Int']['output']>;
  amountTotal?: Maybe<Scalars['Int']['output']>;
  automaticTax: AutomaticTax;
  billingAddressCollection?: Maybe<Scalars['String']['output']>;
  cancelUrl?: Maybe<Scalars['String']['output']>;
  clientReferenceId?: Maybe<Scalars['String']['output']>;
  created: Scalars['ISO8601DateTime']['output'];
  currency?: Maybe<Scalars['String']['output']>;
  customer?: Maybe<Scalars['String']['output']>;
  customerDetails?: Maybe<CustomerDetails>;
  customerEmail?: Maybe<Scalars['String']['output']>;
  id: Scalars['String']['output'];
  lineItems: LineItemListObject;
  livemode: Scalars['Boolean']['output'];
  locale?: Maybe<Scalars['String']['output']>;
  metadata?: Maybe<Scalars['JSON']['output']>;
  mode: Scalars['String']['output'];
  paymentIntent?: Maybe<Scalars['String']['output']>;
  paymentMethodCollection?: Maybe<Scalars['String']['output']>;
  paymentMethodTypes: Array<Scalars['String']['output']>;
  paymentStatus: Scalars['String']['output'];
  stripeObject: Scalars['String']['output'];
  successUrl: Scalars['String']['output'];
  totalDetails: TotalDetails;
  url: Scalars['String']['output'];
};

export type CustomerAddress = {
  __typename?: 'CustomerAddress';
  city?: Maybe<Scalars['String']['output']>;
  country?: Maybe<Scalars['String']['output']>;
  line1?: Maybe<Scalars['String']['output']>;
  line2?: Maybe<Scalars['String']['output']>;
  postalCode?: Maybe<Scalars['String']['output']>;
  state?: Maybe<Scalars['String']['output']>;
};

export type CustomerDetails = {
  __typename?: 'CustomerDetails';
  address?: Maybe<CustomerAddress>;
  email?: Maybe<Scalars['String']['output']>;
  name?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  taxExempt?: Maybe<Scalars['String']['output']>;
  taxIds?: Maybe<Array<Scalars['JSON']['output']>>;
};

/** Autogenerated input type of DemoAdminSessionCreate */
export type DemoAdminSessionCreateInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of DemoAdminSessionCreate. */
export type DemoAdminSessionCreatePayload = {
  __typename?: 'DemoAdminSessionCreatePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors: Array<Error>;
  user?: Maybe<User>;
};

/** Generic error type */
export type Error = {
  __typename?: 'Error';
  message: Scalars['String']['output'];
  path?: Maybe<Array<Scalars['String']['output']>>;
};

export type LineItem = {
  __typename?: 'LineItem';
  amountTotal: Scalars['Int']['output'];
  description: Scalars['String']['output'];
  id: Scalars['String']['output'];
  quantity: Scalars['Int']['output'];
  stripeObject: Scalars['String']['output'];
};

export type LineItemListObject = {
  __typename?: 'LineItemListObject';
  data?: Maybe<Array<LineItem>>;
  hasMore: Scalars['Boolean']['output'];
  stripeObject: Scalars['String']['output'];
  url: Scalars['String']['output'];
};

export type Mutation = {
  __typename?: 'Mutation';
  /** Creates a new session */
  demoAdminSessionCreate?: Maybe<DemoAdminSessionCreatePayload>;
  /** Creates a new session */
  sessionCreate?: Maybe<SessionCreatePayload>;
  /** Logs the current user out */
  sessionDelete?: Maybe<SessionDeletePayload>;
  setOrderActive?: Maybe<SetOrderActivePayload>;
  /** Creates a new stripe_checkout_session */
  stripeCheckoutSessionCreate?: Maybe<StripeCheckoutSessionCreatePayload>;
  /** Creates a new user */
  userCreate?: Maybe<UserCreatePayload>;
};


export type MutationDemoAdminSessionCreateArgs = {
  input: DemoAdminSessionCreateInput;
};


export type MutationSessionCreateArgs = {
  input: SessionCreateInput;
};


export type MutationSessionDeleteArgs = {
  input: SessionDeleteInput;
};


export type MutationSetOrderActiveArgs = {
  input: SetOrderActiveInput;
};


export type MutationStripeCheckoutSessionCreateArgs = {
  input: StripeCheckoutSessionCreateInput;
};


export type MutationUserCreateArgs = {
  input: UserCreateInput;
};

export type Order = {
  __typename?: 'Order';
  createdAt: Scalars['ISO8601DateTime']['output'];
  guestEmail?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  status: Scalars['String']['output'];
  stripeCheckoutSessionLineItems: Array<OrderLineItem>;
  stripePaymentIntentId: Scalars['String']['output'];
  updatedAt: Scalars['ISO8601DateTime']['output'];
  user?: Maybe<User>;
};

export type OrderLineItem = {
  __typename?: 'OrderLineItem';
  name: Scalars['String']['output'];
  quantity: Scalars['Int']['output'];
};

export type OrderPageInput = {
  price: Scalars['String']['input'];
  quantity?: InputMaybe<Scalars['Int']['input']>;
};

export type Product = {
  __typename?: 'Product';
  active: Scalars['Boolean']['output'];
  attributes: Array<Maybe<Scalars['String']['output']>>;
  created: Scalars['ISO8601DateTime']['output'];
  defaultPrice: Scalars['String']['output'];
  description: Scalars['String']['output'];
  id: Scalars['String']['output'];
  images: Array<Maybe<Scalars['String']['output']>>;
  livemode: Scalars['Boolean']['output'];
  marketingFeatures: Scalars['JSON']['output'];
  metadata: Scalars['JSON']['output'];
  name: Scalars['String']['output'];
  packageDimensions?: Maybe<Scalars['JSON']['output']>;
  shippable?: Maybe<Scalars['Boolean']['output']>;
  statementDescriptor?: Maybe<Scalars['String']['output']>;
  stripeObject: Scalars['String']['output'];
  taxCode: Scalars['String']['output'];
  type: Scalars['String']['output'];
  unitLabel?: Maybe<Scalars['String']['output']>;
  updated: Scalars['ISO8601DateTime']['output'];
  url?: Maybe<Scalars['String']['output']>;
};

export type ProductListObject = {
  __typename?: 'ProductListObject';
  data?: Maybe<Array<Product>>;
  hasMore: Scalars['Boolean']['output'];
  stripeObject: Scalars['String']['output'];
  url: Scalars['String']['output'];
};

export type Query = {
  __typename?: 'Query';
  currentUser?: Maybe<User>;
  fetchCheckoutSession?: Maybe<CheckoutSession>;
  listProducts: ProductListObject;
  orders?: Maybe<Array<Order>>;
  retrieveProduct?: Maybe<Product>;
};


export type QueryFetchCheckoutSessionArgs = {
  id: Scalars['ID']['input'];
};


export type QueryRetrieveProductArgs = {
  productId: Scalars['String']['input'];
};

/** Autogenerated input type of SessionCreate */
export type SessionCreateInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  sessionInput: SessionInput;
};

/** Autogenerated return type of SessionCreate. */
export type SessionCreatePayload = {
  __typename?: 'SessionCreatePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors: Array<Error>;
  user?: Maybe<User>;
};

/** Autogenerated input type of SessionDelete */
export type SessionDeleteInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of SessionDelete. */
export type SessionDeletePayload = {
  __typename?: 'SessionDeletePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors: Array<Error>;
  user?: Maybe<User>;
};

export type SessionInput = {
  email: Scalars['String']['input'];
  password: Scalars['String']['input'];
};

/** Autogenerated input type of SetOrderActive */
export type SetOrderActiveInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['ID']['input'];
};

/** Autogenerated return type of SetOrderActive. */
export type SetOrderActivePayload = {
  __typename?: 'SetOrderActivePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  order: Order;
};

/** Autogenerated input type of StripeCheckoutSessionCreate */
export type StripeCheckoutSessionCreateInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  stripeCheckoutSessionInput: StripeCheckoutSessionInput;
};

/** Autogenerated return type of StripeCheckoutSessionCreate. */
export type StripeCheckoutSessionCreatePayload = {
  __typename?: 'StripeCheckoutSessionCreatePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors: Array<Error>;
  stripeCheckoutSession?: Maybe<CheckoutSession>;
};

export type StripeCheckoutSessionInput = {
  lineItems: Array<OrderPageInput>;
};

export type TotalDetails = {
  __typename?: 'TotalDetails';
  amountDiscount: Scalars['Int']['output'];
  amountShipping: Scalars['Int']['output'];
  amountTax: Scalars['Int']['output'];
};

export type User = {
  __typename?: 'User';
  admin: Scalars['Boolean']['output'];
  createdAt: Scalars['ISO8601DateTime']['output'];
  email: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  stripeCustomerId?: Maybe<Scalars['String']['output']>;
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

/** Autogenerated input type of UserCreate */
export type UserCreateInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  userInput: UserInput;
};

/** Autogenerated return type of UserCreate. */
export type UserCreatePayload = {
  __typename?: 'UserCreatePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors: Array<Error>;
  user?: Maybe<User>;
};

export type UserInput = {
  email: Scalars['String']['input'];
  id?: InputMaybe<Scalars['ID']['input']>;
  password: Scalars['String']['input'];
  passwordConfirmation: Scalars['String']['input'];
  stripeCustomerId?: InputMaybe<Scalars['String']['input']>;
};

export type GetProductsQueryVariables = Exact<{ [key: string]: never; }>;


export type GetProductsQuery = { __typename?: 'Query', listProducts: { __typename?: 'ProductListObject', stripeObject: string, hasMore: boolean, url: string, data?: Array<{ __typename?: 'Product', defaultPrice: string, description: string, name: string }> | null } };

export type StripeCheckoutSessionCreateMutationVariables = Exact<{
  input: StripeCheckoutSessionCreateInput;
}>;


export type StripeCheckoutSessionCreateMutation = { __typename?: 'Mutation', stripeCheckoutSessionCreate?: { __typename?: 'StripeCheckoutSessionCreatePayload', stripeCheckoutSession?: { __typename?: 'CheckoutSession', url: string } | null, errors: Array<{ __typename?: 'Error', message: string }> } | null };

export type SetOrderActiveMutationVariables = Exact<{
  input: SetOrderActiveInput;
}>;


export type SetOrderActiveMutation = { __typename?: 'Mutation', setOrderActive?: { __typename?: 'SetOrderActivePayload', order: { __typename?: 'Order', id: string, status: string } } | null };

export type FetchOrdersQueryVariables = Exact<{ [key: string]: never; }>;


export type FetchOrdersQuery = { __typename?: 'Query', orders?: Array<{ __typename?: 'Order', id: string, status: string, guestEmail?: string | null, stripeCheckoutSessionLineItems: Array<{ __typename?: 'OrderLineItem', name: string, quantity: number }>, user?: { __typename?: 'User', id: string, email: string } | null }> | null };

export type DemoAdminSessionCreateMutationVariables = Exact<{
  input: DemoAdminSessionCreateInput;
}>;


export type DemoAdminSessionCreateMutation = { __typename?: 'Mutation', demoAdminSessionCreate?: { __typename?: 'DemoAdminSessionCreatePayload', user?: { __typename?: 'User', id: string, email: string } | null } | null };

export type CurrentUserQueryVariables = Exact<{ [key: string]: never; }>;


export type CurrentUserQuery = { __typename?: 'Query', currentUser?: { __typename?: 'User', id: string, email: string, admin: boolean } | null };

export type SessionDeleteMutationVariables = Exact<{ [key: string]: never; }>;


export type SessionDeleteMutation = { __typename?: 'Mutation', sessionDelete?: { __typename?: 'SessionDeletePayload', user?: { __typename?: 'User', id: string } | null, errors: Array<{ __typename?: 'Error', message: string, path?: Array<string> | null }> } | null };

export type CreateSessionMutationVariables = Exact<{
  input: SessionCreateInput;
}>;


export type CreateSessionMutation = { __typename?: 'Mutation', sessionCreate?: { __typename?: 'SessionCreatePayload', user?: { __typename?: 'User', id: string } | null, errors: Array<{ __typename?: 'Error', message: string, path?: Array<string> | null }> } | null };

export type FetchStripeCheckoutSessionQueryVariables = Exact<{
  id: Scalars['ID']['input'];
}>;


export type FetchStripeCheckoutSessionQuery = { __typename?: 'Query', fetchCheckoutSession?: { __typename?: 'CheckoutSession', id: string, amountTotal?: number | null, lineItems: { __typename?: 'LineItemListObject', hasMore: boolean, data?: Array<{ __typename?: 'LineItem', id: string, amountTotal: number, description: string, quantity: number }> | null } } | null };

export type CreateUserMutationVariables = Exact<{
  input: UserCreateInput;
}>;


export type CreateUserMutation = { __typename?: 'Mutation', userCreate?: { __typename?: 'UserCreatePayload', user?: { __typename?: 'User', id: string, email: string } | null, errors: Array<{ __typename?: 'Error', message: string, path?: Array<string> | null }> } | null };


export const GetProductsDocument = gql`
    query GetProducts {
  listProducts {
    stripeObject
    hasMore
    url
    data {
      defaultPrice
      description
      name
    }
  }
}
    `;

/**
 * __useGetProductsQuery__
 *
 * To run a query within a React component, call `useGetProductsQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetProductsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetProductsQuery({
 *   variables: {
 *   },
 * });
 */
export function useGetProductsQuery(baseOptions?: Apollo.QueryHookOptions<GetProductsQuery, GetProductsQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<GetProductsQuery, GetProductsQueryVariables>(GetProductsDocument, options);
      }
export function useGetProductsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<GetProductsQuery, GetProductsQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<GetProductsQuery, GetProductsQueryVariables>(GetProductsDocument, options);
        }
export function useGetProductsSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<GetProductsQuery, GetProductsQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<GetProductsQuery, GetProductsQueryVariables>(GetProductsDocument, options);
        }
export type GetProductsQueryHookResult = ReturnType<typeof useGetProductsQuery>;
export type GetProductsLazyQueryHookResult = ReturnType<typeof useGetProductsLazyQuery>;
export type GetProductsSuspenseQueryHookResult = ReturnType<typeof useGetProductsSuspenseQuery>;
export type GetProductsQueryResult = Apollo.QueryResult<GetProductsQuery, GetProductsQueryVariables>;
export const StripeCheckoutSessionCreateDocument = gql`
    mutation StripeCheckoutSessionCreate($input: StripeCheckoutSessionCreateInput!) {
  stripeCheckoutSessionCreate(input: $input) {
    stripeCheckoutSession {
      url
    }
    errors {
      message
    }
  }
}
    `;
export type StripeCheckoutSessionCreateMutationFn = Apollo.MutationFunction<StripeCheckoutSessionCreateMutation, StripeCheckoutSessionCreateMutationVariables>;

/**
 * __useStripeCheckoutSessionCreateMutation__
 *
 * To run a mutation, you first call `useStripeCheckoutSessionCreateMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useStripeCheckoutSessionCreateMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [stripeCheckoutSessionCreateMutation, { data, loading, error }] = useStripeCheckoutSessionCreateMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export function useStripeCheckoutSessionCreateMutation(baseOptions?: Apollo.MutationHookOptions<StripeCheckoutSessionCreateMutation, StripeCheckoutSessionCreateMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<StripeCheckoutSessionCreateMutation, StripeCheckoutSessionCreateMutationVariables>(StripeCheckoutSessionCreateDocument, options);
      }
export type StripeCheckoutSessionCreateMutationHookResult = ReturnType<typeof useStripeCheckoutSessionCreateMutation>;
export type StripeCheckoutSessionCreateMutationResult = Apollo.MutationResult<StripeCheckoutSessionCreateMutation>;
export type StripeCheckoutSessionCreateMutationOptions = Apollo.BaseMutationOptions<StripeCheckoutSessionCreateMutation, StripeCheckoutSessionCreateMutationVariables>;
export const SetOrderActiveDocument = gql`
    mutation SetOrderActive($input: SetOrderActiveInput!) {
  setOrderActive(input: $input) {
    order {
      id
      status
    }
  }
}
    `;
export type SetOrderActiveMutationFn = Apollo.MutationFunction<SetOrderActiveMutation, SetOrderActiveMutationVariables>;

/**
 * __useSetOrderActiveMutation__
 *
 * To run a mutation, you first call `useSetOrderActiveMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useSetOrderActiveMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [setOrderActiveMutation, { data, loading, error }] = useSetOrderActiveMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export function useSetOrderActiveMutation(baseOptions?: Apollo.MutationHookOptions<SetOrderActiveMutation, SetOrderActiveMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<SetOrderActiveMutation, SetOrderActiveMutationVariables>(SetOrderActiveDocument, options);
      }
export type SetOrderActiveMutationHookResult = ReturnType<typeof useSetOrderActiveMutation>;
export type SetOrderActiveMutationResult = Apollo.MutationResult<SetOrderActiveMutation>;
export type SetOrderActiveMutationOptions = Apollo.BaseMutationOptions<SetOrderActiveMutation, SetOrderActiveMutationVariables>;
export const FetchOrdersDocument = gql`
    query FetchOrders {
  orders {
    id
    status
    stripeCheckoutSessionLineItems {
      name
      quantity
    }
    user {
      id
      email
    }
    guestEmail
  }
}
    `;

/**
 * __useFetchOrdersQuery__
 *
 * To run a query within a React component, call `useFetchOrdersQuery` and pass it any options that fit your needs.
 * When your component renders, `useFetchOrdersQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useFetchOrdersQuery({
 *   variables: {
 *   },
 * });
 */
export function useFetchOrdersQuery(baseOptions?: Apollo.QueryHookOptions<FetchOrdersQuery, FetchOrdersQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<FetchOrdersQuery, FetchOrdersQueryVariables>(FetchOrdersDocument, options);
      }
export function useFetchOrdersLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<FetchOrdersQuery, FetchOrdersQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<FetchOrdersQuery, FetchOrdersQueryVariables>(FetchOrdersDocument, options);
        }
export function useFetchOrdersSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<FetchOrdersQuery, FetchOrdersQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<FetchOrdersQuery, FetchOrdersQueryVariables>(FetchOrdersDocument, options);
        }
export type FetchOrdersQueryHookResult = ReturnType<typeof useFetchOrdersQuery>;
export type FetchOrdersLazyQueryHookResult = ReturnType<typeof useFetchOrdersLazyQuery>;
export type FetchOrdersSuspenseQueryHookResult = ReturnType<typeof useFetchOrdersSuspenseQuery>;
export type FetchOrdersQueryResult = Apollo.QueryResult<FetchOrdersQuery, FetchOrdersQueryVariables>;
export const DemoAdminSessionCreateDocument = gql`
    mutation DemoAdminSessionCreate($input: DemoAdminSessionCreateInput!) {
  demoAdminSessionCreate(input: $input) {
    user {
      id
      email
    }
  }
}
    `;
export type DemoAdminSessionCreateMutationFn = Apollo.MutationFunction<DemoAdminSessionCreateMutation, DemoAdminSessionCreateMutationVariables>;

/**
 * __useDemoAdminSessionCreateMutation__
 *
 * To run a mutation, you first call `useDemoAdminSessionCreateMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useDemoAdminSessionCreateMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [demoAdminSessionCreateMutation, { data, loading, error }] = useDemoAdminSessionCreateMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export function useDemoAdminSessionCreateMutation(baseOptions?: Apollo.MutationHookOptions<DemoAdminSessionCreateMutation, DemoAdminSessionCreateMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<DemoAdminSessionCreateMutation, DemoAdminSessionCreateMutationVariables>(DemoAdminSessionCreateDocument, options);
      }
export type DemoAdminSessionCreateMutationHookResult = ReturnType<typeof useDemoAdminSessionCreateMutation>;
export type DemoAdminSessionCreateMutationResult = Apollo.MutationResult<DemoAdminSessionCreateMutation>;
export type DemoAdminSessionCreateMutationOptions = Apollo.BaseMutationOptions<DemoAdminSessionCreateMutation, DemoAdminSessionCreateMutationVariables>;
export const CurrentUserDocument = gql`
    query CurrentUser {
  currentUser {
    id
    email
    admin
  }
}
    `;

/**
 * __useCurrentUserQuery__
 *
 * To run a query within a React component, call `useCurrentUserQuery` and pass it any options that fit your needs.
 * When your component renders, `useCurrentUserQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useCurrentUserQuery({
 *   variables: {
 *   },
 * });
 */
export function useCurrentUserQuery(baseOptions?: Apollo.QueryHookOptions<CurrentUserQuery, CurrentUserQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<CurrentUserQuery, CurrentUserQueryVariables>(CurrentUserDocument, options);
      }
export function useCurrentUserLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<CurrentUserQuery, CurrentUserQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<CurrentUserQuery, CurrentUserQueryVariables>(CurrentUserDocument, options);
        }
export function useCurrentUserSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<CurrentUserQuery, CurrentUserQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<CurrentUserQuery, CurrentUserQueryVariables>(CurrentUserDocument, options);
        }
export type CurrentUserQueryHookResult = ReturnType<typeof useCurrentUserQuery>;
export type CurrentUserLazyQueryHookResult = ReturnType<typeof useCurrentUserLazyQuery>;
export type CurrentUserSuspenseQueryHookResult = ReturnType<typeof useCurrentUserSuspenseQuery>;
export type CurrentUserQueryResult = Apollo.QueryResult<CurrentUserQuery, CurrentUserQueryVariables>;
export const SessionDeleteDocument = gql`
    mutation SessionDelete {
  sessionDelete(input: {}) {
    user {
      id
    }
    errors {
      message
      path
    }
  }
}
    `;
export type SessionDeleteMutationFn = Apollo.MutationFunction<SessionDeleteMutation, SessionDeleteMutationVariables>;

/**
 * __useSessionDeleteMutation__
 *
 * To run a mutation, you first call `useSessionDeleteMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useSessionDeleteMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [sessionDeleteMutation, { data, loading, error }] = useSessionDeleteMutation({
 *   variables: {
 *   },
 * });
 */
export function useSessionDeleteMutation(baseOptions?: Apollo.MutationHookOptions<SessionDeleteMutation, SessionDeleteMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<SessionDeleteMutation, SessionDeleteMutationVariables>(SessionDeleteDocument, options);
      }
export type SessionDeleteMutationHookResult = ReturnType<typeof useSessionDeleteMutation>;
export type SessionDeleteMutationResult = Apollo.MutationResult<SessionDeleteMutation>;
export type SessionDeleteMutationOptions = Apollo.BaseMutationOptions<SessionDeleteMutation, SessionDeleteMutationVariables>;
export const CreateSessionDocument = gql`
    mutation CreateSession($input: SessionCreateInput!) {
  sessionCreate(input: $input) {
    user {
      id
    }
    errors {
      message
      path
    }
  }
}
    `;
export type CreateSessionMutationFn = Apollo.MutationFunction<CreateSessionMutation, CreateSessionMutationVariables>;

/**
 * __useCreateSessionMutation__
 *
 * To run a mutation, you first call `useCreateSessionMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreateSessionMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createSessionMutation, { data, loading, error }] = useCreateSessionMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export function useCreateSessionMutation(baseOptions?: Apollo.MutationHookOptions<CreateSessionMutation, CreateSessionMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<CreateSessionMutation, CreateSessionMutationVariables>(CreateSessionDocument, options);
      }
export type CreateSessionMutationHookResult = ReturnType<typeof useCreateSessionMutation>;
export type CreateSessionMutationResult = Apollo.MutationResult<CreateSessionMutation>;
export type CreateSessionMutationOptions = Apollo.BaseMutationOptions<CreateSessionMutation, CreateSessionMutationVariables>;
export const FetchStripeCheckoutSessionDocument = gql`
    query FetchStripeCheckoutSession($id: ID!) {
  fetchCheckoutSession(id: $id) {
    id
    amountTotal
    lineItems {
      hasMore
      data {
        id
        amountTotal
        description
        quantity
      }
    }
  }
}
    `;

/**
 * __useFetchStripeCheckoutSessionQuery__
 *
 * To run a query within a React component, call `useFetchStripeCheckoutSessionQuery` and pass it any options that fit your needs.
 * When your component renders, `useFetchStripeCheckoutSessionQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useFetchStripeCheckoutSessionQuery({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useFetchStripeCheckoutSessionQuery(baseOptions: Apollo.QueryHookOptions<FetchStripeCheckoutSessionQuery, FetchStripeCheckoutSessionQueryVariables> & ({ variables: FetchStripeCheckoutSessionQueryVariables; skip?: boolean; } | { skip: boolean; }) ) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<FetchStripeCheckoutSessionQuery, FetchStripeCheckoutSessionQueryVariables>(FetchStripeCheckoutSessionDocument, options);
      }
export function useFetchStripeCheckoutSessionLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<FetchStripeCheckoutSessionQuery, FetchStripeCheckoutSessionQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<FetchStripeCheckoutSessionQuery, FetchStripeCheckoutSessionQueryVariables>(FetchStripeCheckoutSessionDocument, options);
        }
export function useFetchStripeCheckoutSessionSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<FetchStripeCheckoutSessionQuery, FetchStripeCheckoutSessionQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<FetchStripeCheckoutSessionQuery, FetchStripeCheckoutSessionQueryVariables>(FetchStripeCheckoutSessionDocument, options);
        }
export type FetchStripeCheckoutSessionQueryHookResult = ReturnType<typeof useFetchStripeCheckoutSessionQuery>;
export type FetchStripeCheckoutSessionLazyQueryHookResult = ReturnType<typeof useFetchStripeCheckoutSessionLazyQuery>;
export type FetchStripeCheckoutSessionSuspenseQueryHookResult = ReturnType<typeof useFetchStripeCheckoutSessionSuspenseQuery>;
export type FetchStripeCheckoutSessionQueryResult = Apollo.QueryResult<FetchStripeCheckoutSessionQuery, FetchStripeCheckoutSessionQueryVariables>;
export const CreateUserDocument = gql`
    mutation CreateUser($input: UserCreateInput!) {
  userCreate(input: $input) {
    user {
      id
      email
    }
    errors {
      message
      path
    }
  }
}
    `;
export type CreateUserMutationFn = Apollo.MutationFunction<CreateUserMutation, CreateUserMutationVariables>;

/**
 * __useCreateUserMutation__
 *
 * To run a mutation, you first call `useCreateUserMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreateUserMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createUserMutation, { data, loading, error }] = useCreateUserMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export function useCreateUserMutation(baseOptions?: Apollo.MutationHookOptions<CreateUserMutation, CreateUserMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<CreateUserMutation, CreateUserMutationVariables>(CreateUserDocument, options);
      }
export type CreateUserMutationHookResult = ReturnType<typeof useCreateUserMutation>;
export type CreateUserMutationResult = Apollo.MutationResult<CreateUserMutation>;
export type CreateUserMutationOptions = Apollo.BaseMutationOptions<CreateUserMutation, CreateUserMutationVariables>;