default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary: &primary_development
    <<: *default
    database: dairy_free_food_development
    host: localhost
    user: postgres
    password: postgres
  queue:
    <<: *primary_development
    database: dairy_free_food_development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_development
    database: dairy_free_food_cable
    migrations_paths: db/cable_migrate
test:
  <<: *default
  database: dairy_free_food_test
  host: localhost
  user: postgres
  password: postgres
production:
  primary: &primary_production
    <<: *default
    url: <%= Rails.application.credentials.dig(:db, :connection_string) %>
  queue:
    <<: *primary_production
    database: dairy_free_food_queue
    migration_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: dairy_free_food_cable
    migrations_paths: db/cable_migrate
